swagger: "2.0"
info:
  version: "0.0.1"
  title: Todolisto
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
#securityDefinitions:
 # Bearer:
  #  type: apiKey
   # name: Authorization
    #in: header
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /tareas:
    # our controller name
    x-swagger-router-controller: tarea
    get:
      description: Obtener la lista de tareas
      operationId: getTareas
      # define the type of response for Success "200" and Error
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Tarea"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Errors"
    post:
      description: Añadir una nueva tarea
      operationId: postTarea
      # movie info to be stored
      parameters:
        - name: data
          description: Atributos de tarea
          in: body
          required: true
          schema:
            $ref: "#/definitions/RequestTarea"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ResponseTarea"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Errors"
 
  
# complex objects have schema definitions
definitions:

  Tarea:
    type: object
    properties:
      titulo:
        type: string
        description: Nombre de la tarea a realizar
      descripcion:
        type: string
        description: descripcion
      fecha_inicio:
        type: string
        format: date-time
        description: fecha en la cual se crea la tarea.
      fecha_termino:
        type: string
        format: date-time
        description: fecha en la cual termina la tarea
      estado:
        type: number
        description: id del estado
      nombre_estado:
        type: string
        description: nombre del estado de la tarea
      
  Errors:
    type: object
    properties:
      errors:
        type: array
        items:
          type: object
          properties:
            titulo:
              type: string
            detalle:
              type: string
            link:
              type: string
            estado:
              type: string

  ResponseTarea:
    type: object
    properties:
      link:
        type: string
      data:
        type: array
        items:
          $ref: "#/definitions/Tarea"
      type:
        type: string
        
  RequestTarea:
    type: object
    properties:
      titulo:
        type: string
        description: Nombre de la tarea
      descripcion:
        type: string
        description: Ingrese una breve descripcion
      fecha_inicio:
        type: string
        format: date-time
        description: Fecha en la cual comienza la tarea(dejar en blanco)
      fecha_termino:
        type: string
        format: date-time
        description: Fecha de termino para la tarea (dejar en blanco)
      estado:
        type: number
        description: id del estado
      nombre_estado:
        type: string
